/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.junit.jupiter:junit-jupiter:5.8.2")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.2")

    implementation("org.springframework.boot:spring-boot-starter-web:2.6.7")
    implementation("org.springframework.boot:spring-boot-starter-hateoas:2.6.7")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.6.7")

    testImplementation("junit:junit-dep:4.11")
    testImplementation("org.mockito:mockito-core:4.4.0")
    testImplementation("org.hamcrest:hamcrest-library:2.2")

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.2")


    implementation ("javax.validation:validation-api:2.0.1.Final")
    implementation ("org.hibernate:hibernate-validator:6.0.2.Final")
}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
